const fs = require('fs');

function htmlToReact(html, componentName) {
  // Extract body inner HTML
  let bodyContent = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
  if (!bodyContent) return '';
  let content = bodyContent[1];
  
  // Basic React replacements
  content = content.replace(/class=/g, 'className=')
                   .replace(/<!--([\s\S]*?)-->/g, '{/* $1 */}')
                   .replace(/for=/g, 'htmlFor=')
                   .replace(/<input([^>]*[^\/])>/g, '<input$1 />')
                   .replace(/<img([^>]*[^\/])>/g, '<img$1 />')
                   .replace(/<br([^>]*[^\/])>/g, '<br$1 />')
                   .replace(/<hr([^>]*[^\/])>/g, '<hr$1 />')
                   .replace(/disabled=""/g, 'disabled');
                   
  // We need to wrap it inside a single root element if there are multiple root elements, but body innerHTML usually has a single top-level div if generated by Stitch. Let's just wrap it in <> </>.
  
  return `import React from 'react';\nimport Icon from '@/components/ui/Icon';\n\nconst ${componentName}: React.FC = () => {\n  return (\n    <div className="w-full h-full overflow-y-auto">\n${content}\n    </div>\n  );\n};\n\nexport default ${componentName};\n`;
}

try {
  let mfHtml = fs.readFileSync('manufacturer.html', 'utf8');
  let mapHtml = fs.readFileSync('map.html', 'utf8');
  
  fs.writeFileSync('src/pages/officer/ManufacturerRepeat.tsx', htmlToReact(mfHtml, 'ManufacturerRepeat').replace(/@\/components/g, '../../components'));
  fs.writeFileSync('src/pages/officer/Map.tsx', htmlToReact(mapHtml, 'Map').replace(/@\/components/g, '../../components'));
} catch (err) {
  console.error(err);
}
