"""add share token fields to report

Revision ID: 1b35418670dd
Revises: 9f0769a301bf
Create Date: 2026-09-11 20:14:52.036550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b35418670dd'
down_revision: Union[str, Sequence[str], None] = '9f0769a301bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('share_token_hash', sa.String(length=255), nullable=True))
    op.add_column('reports', sa.Column('share_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'share_expires_at')
    op.drop_column('reports', 'share_token_hash')
    # ### end Alembic commands ###
