"""initial_schema_14_tables_with_constraints

Revision ID: 1d605ea4b436
Revises: 
Create Date: 2026-09-06 16:25:45.471174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d605ea4b436'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturers_name'), 'manufacturers', ['name'], unique=False)
    op.create_index(op.f('ix_manufacturers_normalized_name'), 'manufacturers', ['normalized_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('USER', 'OFFICER', 'ADMIN')", name='check_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('officers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_number', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('jurisdiction', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officers_badge_number'), 'officers', ['badge_number'], unique=False)
    op.create_index(op.f('ix_officers_user_id'), 'officers', ['user_id'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manufacturer_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_manufacturer_id'), 'products', ['manufacturer_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_code', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('officer_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('manufacturer_id', sa.UUID(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('compliance_status', sa.String(length=20), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=True),
    sa.Column('review_reason', sa.String(length=50), nullable=True),
    sa.Column('applicability_status', sa.String(length=20), nullable=True),
    sa.Column('applicable_rule_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('product_name_ai', sa.String(length=500), nullable=True),
    sa.Column('product_category_ai', sa.String(length=100), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('package_context', sa.String(length=100), nullable=True),
    sa.Column('context_confidence', sa.Float(), nullable=True),
    sa.Column('relevant_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('location_text', sa.String(length=500), nullable=True),
    sa.Column('ocr_version', sa.String(length=50), nullable=True),
    sa.Column('classification_model_version', sa.String(length=50), nullable=True),
    sa.Column('embedding_model_version', sa.String(length=50), nullable=True),
    sa.Column('llm_version', sa.String(length=50), nullable=True),
    sa.Column('rag_version', sa.String(length=50), nullable=True),
    sa.Column('rule_engine_version', sa.String(length=50), nullable=True),
    sa.Column('legal_corpus_version', sa.String(length=50), nullable=True),
    sa.Column('officer_notes', sa.Text(), nullable=True),
    sa.Column('inspection_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("applicability_status IN ('DETERMINED', 'REVIEW_REQUIRED')", name='check_applicability_status'),
    sa.CheckConstraint("compliance_status IN ('COMPLIANT', 'NON_COMPLIANT', 'INCONCLUSIVE')", name='check_compliance_status'),
    sa.CheckConstraint("processing_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')", name='check_processing_status'),
    sa.CheckConstraint("review_reason IN ('LOW_IMAGE_QUALITY', 'OCR_UNCERTAIN', 'APPLICABILITY_UNCERTAIN', 'CONFLICTING_INFORMATION', 'PHYSICAL_VERIFICATION_REQUIRED', 'LEGAL_CONTEXT_INSUFFICIENT', 'INSUFFICIENT_EVIDENCE')", name='check_review_reason'),
    sa.CheckConstraint("review_status IN ('NOT_REQUIRED', 'PENDING', 'REVIEWED', 'CONFIRMED', 'REJECTED')", name='check_review_status'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_compliance_status'), 'inspections', ['compliance_status'], unique=False)
    op.create_index(op.f('ix_inspections_created_at'), 'inspections', ['created_at'], unique=False)
    op.create_index(op.f('ix_inspections_inspection_code'), 'inspections', ['inspection_code'], unique=True)
    op.create_index(op.f('ix_inspections_inspection_date'), 'inspections', ['inspection_date'], unique=False)
    op.create_index(op.f('ix_inspections_manufacturer_id'), 'inspections', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_inspections_officer_id'), 'inspections', ['officer_id'], unique=False)
    op.create_index(op.f('ix_inspections_processing_status'), 'inspections', ['processing_status'], unique=False)
    op.create_index(op.f('ix_inspections_product_id'), 'inspections', ['product_id'], unique=False)
    op.create_index(op.f('ix_inspections_user_id'), 'inspections', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('inspection_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_inspection_id'), 'audit_logs', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('inspection_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('image_type', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("image_type IN ('FRONT', 'BACK', 'SIDE', 'LABEL', 'MRP', 'BARCODE', 'QR', 'EVIDENCE', 'OTHER')", name='check_image_type'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_images_inspection_id'), 'inspection_images', ['inspection_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('report_path', sa.String(length=1000), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_inspection_id'), 'reports', ['inspection_id'], unique=False)
    op.create_table('violations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('violation_code', sa.String(length=100), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'REVIEWED', 'CONFIRMED', 'REJECTED', 'RESOLVED')", name='check_violation_status'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violations_inspection_id'), 'violations', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_violations_rule_id'), 'violations', ['rule_id'], unique=False)
    op.create_index(op.f('ix_violations_status'), 'violations', ['status'], unique=False)
    op.create_index(op.f('ix_violations_violation_code'), 'violations', ['violation_code'], unique=False)
    op.create_table('corrective_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('violation_id', sa.UUID(), nullable=True),
    sa.Column('violation_reference', sa.String(length=100), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrective_actions_inspection_id'), 'corrective_actions', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_corrective_actions_violation_id'), 'corrective_actions', ['violation_id'], unique=False)
    op.create_table('declarations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_image_id', sa.UUID(), nullable=True),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("extraction_status IN ('FOUND', 'MISSING', 'UNCERTAIN', 'CONFLICTING')", name='check_extraction_status'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['source_image_id'], ['inspection_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declarations_field_name'), 'declarations', ['field_name'], unique=False)
    op.create_index(op.f('ix_declarations_inspection_id'), 'declarations', ['inspection_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('violation_id', sa.UUID(), nullable=True),
    sa.Column('evidence_id_ai', sa.String(length=100), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('declaration_reference', sa.String(length=100), nullable=True),
    sa.Column('rule_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['inspection_images.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_evidence_id_ai'), 'evidence', ['evidence_id_ai'], unique=False)
    op.create_index(op.f('ix_evidence_inspection_id'), 'evidence', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_evidence_violation_id'), 'evidence', ['violation_id'], unique=False)
    op.create_table('legal_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('violation_id', sa.UUID(), nullable=True),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('rule_number', sa.String(length=100), nullable=True),
    sa.Column('sub_rule', sa.String(length=100), nullable=True),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('legal_version', sa.String(length=50), nullable=True),
    sa.Column('rule_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_references_inspection_id'), 'legal_references', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_legal_references_rule_id'), 'legal_references', ['rule_id'], unique=False)
    op.create_index(op.f('ix_legal_references_violation_id'), 'legal_references', ['violation_id'], unique=False)
    op.create_table('ocr_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('ocr_model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['inspection_images.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_results_image_id'), 'ocr_results', ['image_id'], unique=False)
    op.create_index(op.f('ix_ocr_results_inspection_id'), 'ocr_results', ['inspection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_results_inspection_id'), table_name='ocr_results')
    op.drop_index(op.f('ix_ocr_results_image_id'), table_name='ocr_results')
    op.drop_table('ocr_results')
    op.drop_index(op.f('ix_legal_references_violation_id'), table_name='legal_references')
    op.drop_index(op.f('ix_legal_references_rule_id'), table_name='legal_references')
    op.drop_index(op.f('ix_legal_references_inspection_id'), table_name='legal_references')
    op.drop_table('legal_references')
    op.drop_index(op.f('ix_evidence_violation_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_inspection_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_id_ai'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_declarations_inspection_id'), table_name='declarations')
    op.drop_index(op.f('ix_declarations_field_name'), table_name='declarations')
    op.drop_table('declarations')
    op.drop_index(op.f('ix_corrective_actions_violation_id'), table_name='corrective_actions')
    op.drop_index(op.f('ix_corrective_actions_inspection_id'), table_name='corrective_actions')
    op.drop_table('corrective_actions')
    op.drop_index(op.f('ix_violations_violation_code'), table_name='violations')
    op.drop_index(op.f('ix_violations_status'), table_name='violations')
    op.drop_index(op.f('ix_violations_rule_id'), table_name='violations')
    op.drop_index(op.f('ix_violations_inspection_id'), table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_reports_inspection_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_inspection_images_inspection_id'), table_name='inspection_images')
    op.drop_table('inspection_images')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_inspection_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_inspections_user_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_product_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_processing_status'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_officer_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_manufacturer_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspection_date'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspection_code'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_created_at'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_compliance_status'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_products_manufacturer_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_officers_user_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_badge_number'), table_name='officers')
    op.drop_table('officers')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_manufacturers_normalized_name'), table_name='manufacturers')
    op.drop_index(op.f('ix_manufacturers_name'), table_name='manufacturers')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
