"""Add normalized_unit to declarations

Revision ID: 3d4fd18549ce
Revises: 005aaa77f177
Create Date: 2026-09-11 13:19:05.419999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d4fd18549ce'
down_revision: Union[str, Sequence[str], None] = '005aaa77f177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('declarations', sa.Column('normalized_unit', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('declarations', 'normalized_unit')
    # ### end Alembic commands ###
