"""add_signals_classification_method

Revision ID: 8360f233f70c
Revises: b8c2b0b2620b
Create Date: 2026-09-11 14:29:57.561410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8360f233f70c'
down_revision: Union[str, Sequence[str], None] = 'b8c2b0b2620b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('inspections', sa.Column('classification_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'classification_method')
    op.drop_column('inspections', 'signals')
    # ### end Alembic commands ###
