"""Add enforcement notices table

Revision ID: 9f0769a301bf
Revises: 8360f233f70c
Create Date: 2026-09-11 18:58:24.412049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0769a301bf'
down_revision: Union[str, Sequence[str], None] = '8360f233f70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enforcement_notices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('officer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enforcement_notices_inspection_id'), 'enforcement_notices', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_enforcement_notices_officer_id'), 'enforcement_notices', ['officer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enforcement_notices_officer_id'), table_name='enforcement_notices')
    op.drop_index(op.f('ix_enforcement_notices_inspection_id'), table_name='enforcement_notices')
    op.drop_table('enforcement_notices')
    # ### end Alembic commands ###
