# Standardized violation reason codes for the deterministic rule engine.

MISSING_MRP = "MISSING_MRP"
MISSING_NET_QUANTITY = "MISSING_NET_QUANTITY"
MISSING_MANUFACTURER = "MISSING_MANUFACTURER"
MISSING_CONSUMER_CARE = "MISSING_CONSUMER_CARE"
MISSING_DATE = "MISSING_DATE"
MISSING_COUNTRY_OF_ORIGIN = "MISSING_COUNTRY_OF_ORIGIN"
